language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - composer check

after_success:
  - bash <(curl -s https://codecov.io/bash)